### ISSUE TITLE
Add to cdnjs

### ISSUE THREAD

**Issue by dansup** [jenil/bulmaswatch#1]
Hello,

Great work! These themes are excellent. A few months ago I was looking for exactly this but could only find [bulmathemes](http://bulmathemes.com/), which doesn't seem finished.

Anyways, I was looking to use this project to showcase various themed [bulma templates](https://github.com/dansup/bulma-templates) and I was wondering if you had considered submitting your project to [cdnjs](https://cdnjs.com/) so I could easily include the latest version of each theme.

Cheers

**Comment by jenil** [comment]
Hey,

Thanks!

Yes, that's on the list. I just created a request to add, track here https://github.com/cdnjs/cdnjs/issues/10823

Cheers ☕️

**Comment by fenwick67** [comment]
Hey @jenil it looks like they closed your request because the repo wasn't popular enough, but now you have over 100 stars so you meet [their popularity requirements](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md).  Would you be able to open another issue?

**Comment by jenil** [comment]
Folks, there is a PR under review, track here https://github.com/cdnjs/cdnjs/pull/11339

**Comment by jenil** [comment]
Added to cdnjs https://cdnjs.com/libraries/bulmaswatch
