### ISSUE TITLE
Update to 0.4.3

### ISSUE THREAD

**Issue by Nikpds** [jenil/bulmaswatch#10]
is it possible to update themes to bulma version (missing things like breadcrumb)

**Comment by jenil** [comment]
yes, definitely, will be on the 0.4.3 update this weekend 👨🏻‍💻

**Comment by jenil** [comment]
this is going to take longer than expected. please track the [v0.4.3](https://github.com/jenil/bulmaswatch/tree/v0.4.3) branch in the meantime
