### ISSUE TITLE
Documentation: Navbar Dropdown on "Help" page has incorrect text colors

### ISSUE THREAD

**Issue by cdwieber** [jenil/bulmaswatch#104]
On this specific page: https://jenil.github.io/bulmaswatch/help/

The text color for the "Themes" dropdown menu items is white on a white background (the hover state remains unaffected).

![image](https://user-images.githubusercontent.com/4976963/150380893-af4ac9f2-0ebf-4caa-8c23-1705fe6b2f9d.png)

Browser: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
OS: macOS Big Sur, 11.5 (20G71) (Intel Core i5)

Also tested on Safari.

**Comment by jenil** [comment]
See #29
