### ISSUE TITLE
"Error: Undefined variable: $button-focus-border" in _overrides.scss for Darkly

### ISSUE THREAD

**Issue by ByteOfMelon** [jenil/bulmaswatch#12]
Hi, I'm having an issue importing Bulmaswatch's Darkly into my project.

Here's the error:

"Error: Undefined variable: "$button-focus-border"         
on line 39 of _overrides.scss"

I'm using Bulmaswatch 0.4.3, Bulma 0.4.3

Is this variable needed at all?

**Comment by ByteOfMelon** [comment]
Never mind, i'm just dumb lmao

**Comment by djasnowski** [comment]
What was the answer? I am having the same problem @TheRandomMelon  @jenil

**Comment by ByteOfMelon** [comment]
@naknode what version of Bulmaswatch and Bulma are you using?

**Comment by djasnowski** [comment]
@TheRandomMelon  No worries. I decided to use Semantic UI instead.

**Comment by ByteOfMelon** [comment]
@naknode alright
