### ISSUE TITLE
Update to Bulma 0.5.1

### ISSUE THREAD

**Issue by CopaceticCalypso** [jenil/bulmaswatch#13]
[Bulma Changelog](https://github.com/jgthms/bulma/blob/master/CHANGELOG.md)

With 0.5.0, Bulma did some major variable renaming and things don't compile well with the current 0.4.3 swatch SCSS.

**Comment by jenil** [comment]
Hey, I just pushed 0.5.0, will update to 0.5.1 soon.

**Comment by CopaceticCalypso** [comment]
You rock!
