### ISSUE TITLE
Module build failed:  Undefined variable: "$button-focus-border".

### ISSUE THREAD

**Issue by djasnowski** [jenil/bulmaswatch#15]
Trying to even get this started and I am getting this.

On `app.scss`:

```scss
// Bulma
@import "~bulmaswatch/lux/_variables.scss";
@import "~bulma/bulma.sass";
@import "~bulmaswatch/lux/_overrides.scss";
```

Gives me:

```text
 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed:
undefined
                              ^
      Undefined variable: "$button-focus-border".
      in ~/code/project/node_modules/bulmaswatch/lux/_overrides.scss (line 36, column 32)
```

**Comment by jenil** [comment]
This is an import error, check if you imported `bulma` and `bulmaswatch` correctly

**Comment by djasnowski** [comment]
Hi @jenil 

In my `bula/bulma.sass`, I have:

```sass
@charset "utf-8"
/*! bulma.io v0.5.1 | MIT License | github.com/jgthms/bulma */
@import "sass/utilities/_all"
@import "sass/base/_all"
@import "sass/elements/_all"
@import "sass/components/_all"
@import "sass/grid/_all"
@import "sass/layout/_all"
```

What else do I need? I'm a bit lost here... I cannot find the root bulma and importing `bulma/bulma` does not help. Thanks.

**Comment by jenil** [comment]
How are you compiling? you need to give it the path to `bulma` for it to build properly

**Comment by djasnowski** [comment]
Ah, you're right. I am using Laravel Mix. Thanks!

**Comment by djasnowski** [comment]
I just realized my error @jenil .. I was compoling `.sass` with a `.scss` compiler.  -__- Anyway, thank you!
