### ISSUE TITLE
Solar Theme

### ISSUE THREAD

**Issue by Nikpds** [jenil/bulmaswatch#18]
Good morning everyone. one question about solar theme. After the last update to 0.5.0 the table has white background color  and its doesn't take 100% width of its parent. is it meant to be like this ? Also the button text color has change. I notice also many changes on menu colors . The changed colors are too dark for the rest of the theme.

**Comment by jenil** [comment]
Hey @nikpds, thanks for pointing out, that's probably an issue due to the change in variable naming conventions, I'll fix it.

**Comment by Nikpds** [comment]
Glad i could help.

**Comment by jenil** [comment]
Keeping this open until fixed.
