### ISSUE TITLE
Move navbar out of hero-header

### ISSUE THREAD

**Issue by nedjo** [jenil/bulmaswatch#19]
Thanks for your great work on Bulmaswatch. It's a big attraction of integrating with Bulma. I'm currently working on [adding support for Bulmaswatch to a Drupal theme](https://www.drupal.org/node/2901948).

Some challenges I'm hitting relate to display of the navbar component. I know you've done work as noted in #8. Still, in several themes I'm finding the nav item text is invisible (same colour as the background) in my case.

This arises from two issues:

* Some CSS is limited to `.nav-item` rather than `.navbar-item`.
* Some CSS assumes the navbar is in a `.hero` wrapper.

This compiled CSS rule from the solar theme shows both issues:

```css
.hero.is-primary .nav-item a:not(.button), .hero.is-primary a.nav-item {
    color: #fff;
}
```

An alternative would be:

* In the example pages:
  * Switch from the deprecated `nav` to the `navbar` element.
  * Pull the `navbar` out of the `.hero` and instead place it in its own `<div class="container">` as an immediate child of `<body>`, as is done on bulma.io.
* In the SCSS for the navbar:
  * Where a background color is set, apply it directly rather than relying on the color applied to the `.hero`.

While it would require some changes, this would complete the upgrade from `nav` to `navbar` while making the Bulmaswatch navbar more flexible.

**Comment by jenil** [comment]
I know about the issue, this is mainly coz of 2 reasons:
- New navbar support for hero, which is still being worked on https://github.com/jgthms/bulma/pull/945
- Renaming of variables

I will wait for Bulma to support the navbar inside of a hero and then upgrade the themes. In the meantime, if there is a breaking issue (like invisible text) or an issue caused due to renamed variables, I am happy to push a fix for those.

**Comment by nedjo** [comment]
Great, makes sense, thanks. I'll see if I can work up some pull requests. I'll close this and open other issues as appropriate.

**Comment by nedjo** [comment]
Looked into this some more. My use case is: allow users to switch bulmaswatch themes, meaning the same HTML structure must work for all themes.

The main challenge is if using a navbar in a context where it doesn't use full browser width. This is true for example if using a structure like that on bulma.io, particularly if, like that site, the navbar's container is followed by a hero layout with background color:

```html
<div class="container">
  <nav class="navbar">
  ...
  </nav>
</div>
<section class="hero is-primary">
...
</section>
```
Several bulmaswatch themes set the `$navbar-background-color` variable to other than its default, `$white`. This doesn't work well in this case because the navbar is narrower than the hero layout below it.

A partial workaround is to set the `is-transparent` class on the navbar:

```html
<div class="container">
  <nav class="navbar is-transparent">
```

This results in better display, but:

* the resulting navbar is relatively unstyled in some themes
* there are still issues with border.

So what works best at this point is:

* Have your navbar as a top-level child of the body element.
* Add the `has-shadow` class to separate it from the hero layout below.

**Comment by jenil** [comment]
I totally agree with you on the `$navbar-background-color` set to `$white` issue which is not a good call by the Bulma developer as it has to be overridden even when there are other variables like `$body-background`

Here is another issue with a similar concern https://github.com/jgthms/bulma/issues/837
