### ISSUE TITLE
Sandstone input with button bug

### ISSUE THREAD

**Issue by Nikpds** [jenil/bulmaswatch#21]
I notice a bug in input with attach button. when you set input to large size and to button as well the sizes do not match. i test it on small size too and there is also a difference there. 

Thank you in advance.

**Comment by jenil** [comment]
hey @Nikpds 

Is this what you are talking about?

![image](https://user-images.githubusercontent.com/971411/30434328-00c6dc86-9935-11e7-9ad1-512ff153494b.png)

**Comment by Nikpds** [comment]
yes and something similar happens when you set size to small.
