### ISSUE TITLE
Getting an overflow in .media-content

### ISSUE THREAD

**Issue by maarteNNNN** [jenil/bulmaswatch#27]
# Bug
![screenshotatuploadcc_1519220952262](https://user-images.githubusercontent.com/14275291/36483556-40deed2a-16f5-11e8-8268-ee3439d297be.png)
# Expected behaviour
No overflow at all
# Suggested edit
```
.media-content {
    overflow: hidden;
}
```
# Things I checked
I've compared it to standard Bulma as well as the Superhero style both of them didn't have the bug.
When I look in the element styles:
`overflow: auto`
Opening it says:
```
overflow-x: auto
overflow-y: hidden;
```
# Solution
I haven't checked if it worked only through the developer tools. This was done by unmarking `overflow: auto` and adding `overflow-y: hidden`

**Comment by jenil** [comment]
Hey, I don't see this bug on https://jenil.github.io/bulmaswatch/lux/#card

Can you make a Codepen or fiddle and share it?

**Comment by maarteNNNN** [comment]
I'm not able to get the Lux file in the pen. (I never used Codepen or jsfiddle)

[Pen can be seen here](https://codepen.io/maarteNNNN/pen/gvdjyL)

Edit:
I added the bulma css and the scroll appeared! If you comment bulma.css out it should disappear.

**Comment by jenil** [comment]
Got it, this is an issue with Bulma 0.6.2, try using 0.6.1 and it should work. I'll fix this in the next version.

**Comment by maarteNNNN** [comment]
[here is an issue](https://github.com/jgthms/bulma/issues/1428) on bulma having the same problem
[here is the commit](https://github.com/jgthms/bulma/commit/00801d1e602d004c4283eb265af61338282c77c1) in v0.6.3 this will be fixed on bulma so I think I can close this issue.

**Comment by yrichard** [comment]
I'm having the exact same problem in 0.8.2.
