### ISSUE TITLE
Dropdown color variables

### ISSUE THREAD

**Issue by ghost** [jenil/bulmaswatch#29]
There seems to be some variables that are either missing or not overridden for dropdowns.

Specifically hover color and hover background color.

For reference I'm using Cyborg theme. Hovered dropdown items have black text on dark gray backgrounds and have the exact same hover background. You probably only need to do this for dark themes.

Bulma file: https://github.com/jgthms/bulma/blob/master/sass/components/dropdown.sass

**Comment by kirqe** [comment]
<img width="691" alt="screen shot 2018-03-02 at 01 16 23" src="https://user-images.githubusercontent.com/5272402/36872760-61e5a77a-1db7-11e8-834e-3f5afb0dfe91.png">

**Comment by jenil** [comment]
As you see this is introduced by Bulma itself. I'll update wait till the author fixes it. https://github.com/jgthms/bulma/issues/837

**Comment by ghost** [comment]
@jenil can you at least do a quick check on the Cyborg theme variables?

A dropdown component is being used in the screenshot below.

The first item is hovered (I didn't have a tool to capture the mouse at the moment) and has black text on a dark grey background (the background color doesn't change on hover).

![screenshot from 2018-03-02 17-42-44](https://user-images.githubusercontent.com/8528269/36893051-a6621714-1e41-11e8-9b21-6e681e278ba2.png)

**Comment by jenil** [comment]
I did check that and agree that is a variable issue. I'll fix all the affected themes soon. Look out for the 0.6.3 update by next week.

**Comment by diomed** [comment]
how long is *soon*

because now it's end of September... and you sait that in March

**Comment by ghost** [comment]
@diomed Can you show me a screenshot of the incorrect colors in your project? (I'm not a Bulmaswatch maintainer just a fellow user)

**Comment by diomed** [comment]
I don't see why. You have example screenshot above. 
and this is issue you opened, and it isn't fixed. 
https://jenil.github.io/bulmaswatch/materia/
still looks white on background when one hovers and menu falls down.

actually all white themes have the same problem

**Comment by ghost** [comment]
Calm down, I was just curious what *your* layout looked like with this bug.

**Comment by jenil** [comment]
Here is the origin issue https://github.com/jgthms/bulma/issues/837

**Comment by jenil** [comment]
Also,  FWIW the dropdown color vars were fixed long back.

![image](https://user-images.githubusercontent.com/971411/46125084-29864f00-c245-11e8-9cf1-3660cab961e6.png)


https://jenil.github.io/bulmaswatch/materia/#dropdown

**Comment by diomed** [comment]
do you actually see the screenshot kirqe posted in 2nd post?
look at navigation - navigation dropdown is the issue. 
when you click on themes in navigation, list of links that drop down is not visible at all

**Comment by jenil** [comment]
@diomed I do, please see the origin issue I linked above. The root of the cause is with bulma and not bulmaswatch.

**Comment by diomed** [comment]
so you can't override color?

**Comment by jenil** [comment]
I can, but it makes more sense to fix the issue at its root. If you'd like to fix it, override it in your custom CSS.

**Comment by diomed** [comment]
I think it's your duty to issue a temporary fix and report it to bulma's repo, if you didn't already.
I'll report it myself if you tell me which one is exactly that's wrong.

**Comment by ghost** [comment]
@diomed the maintainer of this project **DOES THIS FOR FREE**.
He has **NO DUTY** to us to fix every little thing in his project, specially considering that this is just a stylesheet which cannot have security bugs.
This problem is **VERY EASY TO PATCH IN YOUR OWN CODE**.
How lazy could you be that you expect the CSS framework to do everything for you?
Just override it, styles cascade, CSS was made to be overriden.
