### ISSUE TITLE
Bulma 0.4.1

### ISSUE THREAD

**Issue by coussej** [jenil/bulmaswatch#3]
Hi there, awesome work on the themes! Much appreciated. I like bulma for the fact that it is just a css file, and being able to replace that file with one of these for themes makes it just too easy 😄 

I was just wondering, any plans on upgrading to Bulma 0.4.1? While most of the style works just fine, some things are missing, like the [new field element](http://bulma.io/2017/03/10/new-field-element/)

Cheers

**Comment by jenil** [comment]
Hey,

Yes, I was waiting for Bulma 0.4.1. I will be updating the themes to 0.4.1 in next 2 weeks or so.

Thanks!

**Comment by jenil** [comment]
Updated to 0.4.1 https://github.com/jenil/bulmaswatch/pull/5
