### ISSUE TITLE
Possible problem with the notifications in some of the themes

### ISSUE THREAD

**Issue by aocneanu** [jenil/bulmaswatch#33]
Hi,

First, thank you for this repo. I use your themes in my [project](https://github.com/laravel-enso/enso) and they add a great value.

There is one problem that I noticed with the notification class in three of the themes: cerulean, simplex and spacelab. In these themes the notification class is transparent, making the notification class unusable in some cases. Do you think that this is something that you would consider addressing?

This is an example from Cerulean:

![image](https://user-images.githubusercontent.com/16073274/37861805-c857fce4-2f49-11e8-9e16-4d2558ef1685.png)

Adi.

**Comment by jenil** [comment]
Gotcha, this is because they use `rgba`, I'll fix this too!

**Comment by jenil** [comment]
hey @aocneanu has this been fixed?

**Comment by aocneanu** [comment]
Hi,

I just tested and it's the exact same behaviour.
