### ISSUE TITLE
Error when compiling lumen

### ISSUE THREAD

**Issue by aocneanu** [jenil/bulmaswatch#34]
When compiling lumen with webpack I get `File to import not found or unreadable: sass/utilities/initial-variables.sass`

https://github.com/jenil/bulmaswatch/blob/gh-pages/lumen/_variables.scss#L4

**Comment by jenil** [comment]
I see, Lumen uses the Bulma `initial-variables` and hence requires them to be imported. I think I will eliminate this in the next release.

**Comment by aocneanu** [comment]
Aham, cool. In my project I do this for all the themes (ex for cerulean). For now I manually removed the import for lumen and the build went well.

```
@import "./node_modules/bulma/sass/utilities/initial-variables";
@import "./node_modules/bulmaswatch/cerulean/variables";
@import "./node_modules/bulma/bulma";
@import "./node_modules/bulmaswatch/cerulean/overrides";
```

**Comment by jenil** [comment]
Fixed in https://github.com/jenil/bulmaswatch/commit/0168e4eb91c9b6a6f0c736fff163ff4356ca9201
will be shipping with 0.6.3

**Comment by Kyslik** [comment]
Why is this closed if its not shipped yet?
