### ISSUE TITLE
Tab colors

### ISSUE THREAD

**Issue by ghost** [jenil/bulmaswatch#35]
Are these white background colors on the tabs intentional or a bug?

I took this screenshot straight from here: http://jenil.github.io/bulmaswatch/cyborg/

![b](https://user-images.githubusercontent.com/8528269/38161110-24addee4-34fb-11e8-9740-f25e39f62c6c.png)

**Comment by jenil** [comment]
It's a bug, not a feature. Thanks for reporting it!

**Comment by ghost** [comment]
@jenil welcome back
