### ISSUE TITLE
Feature request: generate css for Bulma extensions

### ISSUE THREAD

**Issue by piever** [jenil/bulmaswatch#37]
I find it very handy to have a version of a theme available as css using CDN but this has the issue that, when using a [Bulma extension](https://wikiki.github.io/), the widgets from the extension don't get the new theme. I was wondering, if you're using some automated procedure to generate the bulmaswatch.min.css files, whether it would be possible to also generate css for the Bulma extensions (or show in the docs what's a procedure to do that).

**Comment by jenil** [comment]
There is a build process to generate the `bulmaswatch.min.css` files but there is customization for each theme which needs manual CSS changes.

**Comment by piever** [comment]
I managed to reproduce the css build step locally. It turns out that to include extensions in the theme, you can simply add (in your main.scss), after:

```sass
@import bulma
```

the required extensions, for example:

```sass
@import 'bulma-switch/dist/bulma-switch.sass';
```

If you don't mind the slightly increased css side that results from this, maybe it would even be possible to include these extensions by default in the theme css (or maybe to have two versions, extensions and no extensions).

However, while in some cases it works smoothly but in other cases there are unit measure conflicts. For example, if I compile Minty with the "toggle-switch" Bulma extension, I get:

```bash
sass styles/main.scss styles/main.css
Error: Incompatible units rem and px.
  $paddle-height: $switch-height - ($switch-paddle-offset * 2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  vendors/bulma-extensions/bulma-switch/dist/bulma-switch.sass 14:19  switch-size()
  vendors/bulma-extensions/bulma-switch/dist/bulma-switch.sass 148:3  @import
  styles/main.scss 43:9                                               root stylesheet
```

I'm not sure if it's an issue with the theme or the extension. Maybe the theme is changing unit of measure of some bulma quantites?

**Comment by jenil** [comment]
I think have CSS built for extensions separately only makes senses, so I'm going to this issue for now.
