### ISSUE TITLE
Upgrade to latest Bulma

### ISSUE THREAD

**Issue by dsarfati** [jenil/bulmaswatch#38]
We really love the themes you have created. Is there a schedule or process to keep bulmaswatch updated to the latest version of Bulma?

**Comment by jenil** [comment]
Thanks for the love! I have been busy with graduation off late. I'll get on this soon, should be done in a couple of weeks.

**Comment by 0plus1** [comment]
+1 would love the upgrade to latest

**Comment by jfmcbrayer** [comment]
Is it possible to just build the bulmaswatch themes against the latest bulma?

**Comment by jenil** [comment]
Published [0.7.0](https://github.com/jenil/bulmaswatch/releases/tag/v0.7.0)
