### ISSUE TITLE
Progress bars without color modifier are not visible in Darkly theme 

### ISSUE THREAD

**Issue by DJWoodZ** [jenil/bulmaswatch#39]
Hi,

Thank you for this great project!

In the current version (0.7.1), Darkly themed progress bars without a color modifier (e.g. `is-primary`) do not display progress. An example can be seen here: https://jenil.github.io/bulmaswatch/darkly/#progress

I believe this is because `$grey` is used for both the background and default bar color.

**Comment by jenil** [comment]
Hey,

Thanks for reporting this. Yes I believe it is because of the recent updates, I'll fix it.
