### ISSUE TITLE
Recommended customization method

### ISSUE THREAD

**Issue by tehfink** [jenil/bulmaswatch#42]
Thanks for a great project. Sorry if this is a stupid question, but what's the recommended method for customizing a swatch, with an eye towards Bulma and BulmaSwatch updates? So far I've been tweaking `_variables.scss` & `_overrides.scss`.

**Comment by jenil** [comment]
Take a look at [this issue](https://github.com/jenil/bulmaswatch/issues/2) for how to use it with npm/yarn.

I would do something like this:
```scss
@import "~bulma/bulma.sass";
@import "~bulmaswatch/flatly/_variables.scss";
@import "~bulmaswatch/flatly/_overrides.scss";
@import "custom.scss";
```
