### ISSUE TITLE
Navbar default border + has-shadow class =  thick ugly gray line

### ISSUE THREAD

**Issue by ghost** [jenil/bulmaswatch#43]
![633ef21a-3e40-41af-8ce9-7f9b65019b58](https://user-images.githubusercontent.com/8528269/44798364-d38d9f80-abe3-11e8-8fe1-66dad01015a2.png)

I'm wondering why the navbar here has a 1px solid border while the default theme has no border.

The navbar is supposed to have a light/subtle shadow but in this image it becomes a thick gray line.

**Comment by ghost** [comment]
I upgraded from 6.1 to 7.1, that's when I noticed this.

See the image below for the change I noticed in the navbar. The border isn't really the problem, the box-shadow value changed.

![ffcb91aa-c10b-4c02-b229-7e7b5b435b25](https://user-images.githubusercontent.com/8528269/44799137-cf628180-abe5-11e8-9c66-1fab6b6874fe.png)

**Comment by raniesantos** [comment]
## Same problem in other themes

Screenshot for Journal theme:

![screenshot from 2018-08-31 16-55-16](https://user-images.githubusercontent.com/8528269/44903296-bfaa8080-ad3e-11e8-9c68-e981f97cd51a.png)

**Comment by ghost** [comment]
It seems to be a Bulma problem so I posted an issue over there.

jgthms/bulma#2081

Closing...
