### ISSUE TITLE
Would it be possible to make the fonts in the themes optional?

### ISSUE THREAD

**Issue by ghost** [jenil/bulmaswatch#45]
I'm using Journal which has this font in `_overrides.scss`

```css
@import url(https://fonts.googleapis.com/css?family=News+Cycle:400,700);
```

But I also want to use this font that I include through my HTML.

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:200,300">
```

I would much rather **have them both be in the link tag** but News Cycle is hard coded into the overrides.

## Possible solutions:

Sass has control structures right? Can you add a boolean variable + an if-statement to conditionally include this font.

That way I can remove/disable it from my css and then combine it with Raleway in my link tag.

___

A simpler solution might be to add another scss file to the themes with custom fonts.

Add a `_theme-font.scss` file, it should contain just one line, the `@import url(...)`.

This allows me to do the same thing in a different way.

**Comment by jenil** [comment]
I'm not sure what the issue is. Both the fonts load and both can be applied using respective CSS right?
Are you saying you just want to optimize the loading by just 1 web request for fonts?

**Comment by ghost** [comment]
> Are you saying you just want to optimize the loading by just 1 web request for fonts?

Yes, that's exactly what I'm trying to do. I know following PageSpeed isn't absolutely necessary but I just want to clear some of the warnings. The way the themes are setup prevent me from being able to.

Solution no. 2 seems easy enough to implement too.

**Comment by ghost** [comment]
If you're busy I can just make a PR if you confirm you'll merge it.

**Comment by jenil** [comment]
I'm not sure if `_theme-font.scss` is a good idea for such a small thing. If you can make a PR with a Sass conditional variable like `$enable-custom-fonts: true !default` which can control the `@import` then it might work.

**Comment by ghost** [comment]
I guess you're right, both solutions are simple anyway. I might do it tomorrow morning.

**Comment by ghost** [comment]
I've created the PR.

**Comment by jenil** [comment]
cool, will review it over the weekend
