### ISSUE TITLE
Warning text color

### ISSUE THREAD

**Issue by DJWoodZ** [jenil/bulmaswatch#48]
Hi,

Some themes have a light/yellow warning background color with dark text. Other themes, such as Darkly and Flatly have light warning text.

If I enter the yellow color from one of those themes (#F1B70E) into this contrast checker tool: https://webaim.org/resources/contrastchecker/ it suggests that dark text is more accessible.

**Comment by DJWoodZ** [comment]
It might be worth running this tool over the demo pages to see if it identifies any other contrast issues: https://squizlabs.github.io/HTML_CodeSniffer/

**Comment by jenil** [comment]
oh interesting. Thanks, I'll take a look!

**Comment by DJWoodZ** [comment]
Thanks! If you use HTML CodeSniffer it should suggest the closest color that has a good contrast.

**Comment by jenil** [comment]
The closest colours that HTML CodeSniffer suggests is also very far from the current, which kinda doesn't look very nice on the themes.

**Comment by DJWoodZ** [comment]
What about if you switch to a dark font for warnings?

**Comment by jenil** [comment]
Switching to a dark font just for one of the state of the component doesn't look that well. Gonna leave this as it is for now.

**Comment by DJWoodZ** [comment]
That's a shame but I understand. Thank you for taking a look at this.
