### ISSUE TITLE
box element scss variables not present

### ISSUE THREAD

**Issue by thatkookooguy** [jenil/bulmaswatch#51]
can't set any of the scss variables for the Element Box when including the bulmaswatch overrides.

for example: `$box-background-color` is not present, so I can't match that color easily in my scss

should I add them to the `_variables.scss` file?

Also, shouldn't that variable be used in the `_overrides` file? it looks like `$black-ter` is being used instead which is part of the nuclear variables and not the theme variables

**Comment by jenil** [comment]
This is most like as coz the variable was added to Bulma after the theme was initially made. I will be happy to review a PR for this :)

**Comment by thatkookooguy** [comment]
@jenil sure, I'll try and send one this weekend :-)
