### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by ghost** [jenil/bulmaswatch#58]
Hi @jenil,

I've created lots of extension for bulma and templates too. I alos created https://creativbeulma.net marketplace and I'd like to share an opportunity with you. Can you please contact me at gaetan@creativebulma.net so I'll be able to give you more details about it.

Regards,

**Comment by jenil** [comment]
Hi, the website doesn't seem to load. Can you reach out to me with what you have in mind on i@jgog.in? :)

**Comment by ghost** [comment]
Hi,

Sorry I've made a mistake in the url. It's https://creativebulma.net 
Thanks for the email I'll contact you through it.
