### ISSUE TITLE
select with is-multiple in the cerulean swatch has a bug

### ISSUE THREAD

**Issue by hobbyman** [jenil/bulmaswatch#59]
Here, I've created a [codepen](https://codepen.io/hobbyman/pen/XQodKW) to demonstrate the issue.

It seems the issue is with this:  

`.button,.control.has-icons-left .icon,.control.has-icons-right .icon,.input,.pagination-ellipsis,.pagination-link,.pagination-next,.pagination-previous,.select,.select select,.textarea{height:2.375em}`

This is my fix:

`.select, .select select {
    height: auto!important;
}`

**Comment by jenil** [comment]
Pushed in [0.8.1](https://github.com/jenil/bulmaswatch/releases/tag/v0.8.1)

**Comment by kerams** [comment]
A bunch of other themes (united, to name just one) seem to have this problem with `<select multiple size="10">` too.

**Comment by jenil** [comment]
hey @kerams, thanks for reporting! 

Just confirmed this issue still persist in some themes. I'll get to it..

**Comment by rodrigoaguilera** [comment]
I think this is very much solved in the sandstone theme by using the `.select:not(.is-multiple)` selector.
Can't this be applied to every theme?

**Comment by deather** [comment]
This issue was probably fixed with the PR #81 . I try in local the other theme after adding select multiple in templates, and all seem to be OK
