### ISSUE TITLE
Do you take PRs?

### ISSUE THREAD

**Issue by fenwick67** [jenil/bulmaswatch#6]
I was working on a Bulma theme using this repo as a a starting point, would you take a PR with a new theme?  

If so, do you have criteria for themes that "pass muster"?

**Comment by jenil** [comment]
Hey! 

I don't mind mind taking a PR if the theme uses a different aesthetic, and not just mere colour changes. There is no criteria as such but a screenshot of the theme along with the PR and following the coding style is a must.
