### ISSUE TITLE
Can't view theme names on demo pages

### ISSUE THREAD

**Issue by anitagraham** [jenil/bulmaswatch#60]
This may be related to #29, but I can't view the theme names - unless they are hovered - on the demo page.
Just browsing themes it occurs to me that in addition to the dropdown it would be useful to have a page showing all the themes. 

A set of cards with the main colours/typography visible would allow a user to pick and choose rather than running through the whole set of dropdown options page by page.
 
![Drop Down Theme names](https://user-images.githubusercontent.com/397118/57342719-c9f50800-7172-11e9-9e83-4ffded6fb5fe.png)

thanks,
Anita

**Comment by jenil** [comment]
Hey, I am not sure what you mean here. The dropdown is a known issue.
