### ISSUE TITLE
Indicate new releases with git tags

### ISSUE THREAD

**Issue by rodrigoaguilera** [jenil/bulmaswatch#67]
It is a bit confusing to see the release 0.7.5 and the latest tag to be 0.7.2.

I guess npmjs.com scans the repo from time to time and checks if the ```version``` key has changed and releases a new version.

I think it could be simpler with git tags.

Thank you for the awesome project

**Comment by jenil** [comment]
Hey, I realized that all releases were tagged but not pushed to GitHub, I just pushed them!

**Comment by rodrigoaguilera** [comment]
Great :)
