### ISSUE TITLE
Links in hamburgermenu gets same color as background

### ISSUE THREAD

**Issue by danmusk** [jenil/bulmaswatch#7]
When using the "hamburgermenu", the text-color on the links is the same as the links in the main-menu. Resulting in a ex. white links on white background.

**Comment by jenil** [comment]
Hey @danmusk, can you provide a screenshot or some more details like which theme? or a code snippet?

**Comment by danmusk** [comment]
I created a fiddle to show the use case. If you show it in mobile-size, the hamburgermenu will appear and you will see what I mean: https://jsfiddle.net/hewag0a1/2/
Thanks for your work on bulmaswatch!

**Comment by jenil** [comment]
oh I see what you are talking about, will fix it.
