### ISSUE TITLE
Dynamically change theme in React

### ISSUE THREAD

**Issue by tonyjmartinez** [jenil/bulmaswatch#70]
Is there a way to dynamically change the bulma theme in React without reloading the page? Since these themes involve requiring files I'm having trouble figuring out a way to change the theme without doing a `window.location.reload()`.

**Comment by jenil** [comment]
You should be able to do this with swapping the case files. Reload will not be needed then.

**Comment by tonyjmartinez** [comment]
@jenil by case files do you mean `_variables.scss` and `_overrides.scss`? And how would you swap them? I have a solution right now that happens in a `dangerouslySetInnerHtml` but it looks buggy since the whole stylesheet is changing.

**Comment by davetapley** [comment]
@tonyjmartinez did you find a way?
