### ISSUE TITLE
Override _variables.scss in separate .scss file? 

### ISSUE THREAD

**Issue by RobJacobson** [jenil/bulmaswatch#71]
Thanks for making Bulmaswatch!  I'm really liking the Flatly theme.  However, I'm having difficulty overriding the Flatly font (Lato) with a custom font (Nunito).

My setup is:
1.  I installed both Bulma and Bulmaswatch using NPM.
2.  I have a separate "index.scss" file that I'm attempting to use for my own customizations.  It currently has the following structure: 
```
@charset "utf-8";
@import url("https://fonts.googleapis.com/css?family=Nunito:400,700");

$family-sans-serif: "Nunito", sans-serif;
@import "bulmaswatch/flatly/_variables.scss";
@import "bulma/bulma.sass";
@import "bulmaswatch/flatly/_overrides.scss";
```

I'm trying to set $family-sans-serif manually to override the same variable from variables.scss.  Is this possible? I've tried different orderings of the ```$family-sans-serif``` line, without success.

I realize that I can either edit the Flatly variables.scss file or copy-paste its content into a new file, and then make modifications.  However, I would prefer to keep my changes in their own custom .scss file so that I can tell which modifications come from Flatly and which ones are self-created.

Many thanks!

**Comment by jenil** [comment]
you can simply copy the contents of `flatly/_variables.scss` and make your own version of it and import it.
