### ISSUE TITLE
Input text is hardly visible in dark themes by default 

### ISSUE THREAD

**Issue by gabriel4649** [jenil/bulmaswatch#78]
Hi!

First of all, thank you for putting this together. 

Input text is hardly visible in dark themes by default. For example, look at the cyborg theme

![image](https://user-images.githubusercontent.com/232527/77252131-aae75380-6c28-11ea-8111-2dfa8ef310e0.png)

Not sure if this is intended or not.

**Comment by jenil** [comment]
This was after the 0.8.0 update, I'll fix this.

**Comment by kabobrocks** [comment]
any ETA on this @jenil ?

**Comment by jenil** [comment]
I'll get to it this week

**Comment by sunsetsonwheels** [comment]
I'm not sure if this is related but this seems to be a common problem for most of the form controls right now, not just the input, the select ones are broken too.

**Comment by jenil** [comment]
Pushed in https://github.com/jenil/bulmaswatch/releases/tag/v0.8.1
