### ISSUE TITLE
Add support for new navbar component

### ISSUE THREAD

**Issue by jhoff** [jenil/bulmaswatch#8]
Bulma 2.4 introduced the navbar which will eventually replace nav -
 http://bulma.io/documentation/components/navbar/

The following link provides the relevant variables that need to be redefined for each theme:
https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass

**Comment by jenil** [comment]
hey @jhoff this was added in 0.4.3 release with #11

**Comment by jhoff** [comment]
Thanks!
