### ISSUE TITLE
$navbar-breakpoint issue

### ISSUE THREAD

**Issue by elmatou** [jenil/bulmaswatch#86]
Hi,
since Bulma 0.7.5 it is possible to change the breakpoint of the navbar (when the burger menu appear)
Bulma implemented it using `+until($navbar-breakpoint)` & `+from($navbar-breakpoint)`

when bulmaswatch implement it with `@include touch` & `@include desktop` which do not take into consideration `$navbar-breakpoint`

https://github.com/jenil/bulmaswatch/blob/9f392634ff8d6c1fda1fcbabcea28b9f4dd115f4/flatly/_overrides.scss#L141-L183

**Comment by loopmode** [comment]
This is with at least superhero as well 🙂

**Comment by elmatou** [comment]
looking at the code of different template, it seems to be everywhere.
