### ISSUE TITLE
Select dropdown arrow over the select content

### ISSUE THREAD

**Issue by bentayloruk** [jenil/bulmaswatch#9]
Just found bulmswatch today.  Thanks for your hard work.

I was using the current `0.4.2` CDN version of Bulma, like this:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.2/css/bulma.css">`

When I have a select styled, it looks like this (correct):
![image](https://user-images.githubusercontent.com/189409/28250058-f15d4542-6a58-11e7-83f5-697bd5d60572.png)

If I switch over to a bulmaswatch CSS (minified download version), I get this:
![image](https://user-images.githubusercontent.com/189409/28250069-28838900-6a59-11e7-90de-9b7391cd7fa8.png)

My select style looks like this:

```
<span class="select level-item">
<select><option>And</option><option>Or</option></select>
</span>
```
Am I doing something wrong?

**Comment by jenil** [comment]
hey @bentayloruk 

I see what you are talking about, I'll fix the padding in the next update.

**Comment by bentayloruk** [comment]
Awesome, thanks!

**Comment by jenil** [comment]
So getting deeper into the issue this seems to be an issue with the minifier FYI https://github.com/jgthms/bulma/issues/754

Bulmaswatch uses cssnano for the minification and the v4 fixes this issue. will push an update along with the v0.4.3 update.

**Comment by jenil** [comment]
Hey @bentayloruk,

This was fixed in [this commit](https://github.com/jenil/bulmaswatch/commit/fb5d7fece700c82fbe71fcdc9530f7313d3e05c9)
Please try now.

**Comment by bentayloruk** [comment]
Awesome thanks!  Will try it out as soon as I can.

**Comment by bentayloruk** [comment]
Working for me, thank you Sir!
